import TransactionReportsInteractive from './components/TransactionReportsInteractive';

export const metadata = {
  title: 'Transaction Reports - LF Parking Management System',
  description: 'Comprehensive analysis of parking transactions with detailed filtering, search capabilities, and export functionality for operational and financial reporting.'
};

export default function TransactionReportsPage() {
  const mockTransactions = [
    {
      id: 1,
      transaction_id: 'TXN-2024-001234',
      date: '11/18/2024',
      time: '09:15 AM',
      location: 'Pacs',
      license_plate: 'ABC123',
      customer_name: 'John Smith',
      transaction_type: 'Hourly Parking',
      duration: 120,
      pricing_mode: 'Fixed Hourly',
      amount: 15.00,
      payment_method: 'Credit Card',
      payment_reference: 'REF-789012',
      permit_number: null,
      permit_type: null,
      enforcement_action: null,
      violation_id: null,
      discount_applied: null,
      tax_amount: 1.20,
      total_amount: 16.20,
      status: 'Completed',
      processed_by: 'System Auto',
      notes: 'Standard hourly parking transaction',
      entry_time: '09:15 AM',
      exit_time: '11:15 AM',
      space_number: 'A-15',
      zone: 'Zone A',
      card_last_four: '4532',
      auth_code: 'AUTH123456',
      payment_gateway: 'Stripe',
      processor_fee: 0.45,
      created_at: '11/18/2024 09:15:23',
      updated_at: '11/18/2024 11:15:45',
      ip_address: '192.168.1.100',
      user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    },
    {
      id: 2,
      transaction_id: 'TXN-2024-001235',
      date: '11/18/2024',
      time: '10:30 AM',
      location: '11 ST',
      license_plate: 'XYZ789',
      customer_name: 'Sarah Johnson',
      transaction_type: 'Monthly Permit',
      duration: null,
      pricing_mode: 'Monthly Rate',
      amount: 150.00,
      payment_method: 'Debit Card',
      payment_reference: 'REF-789013',
      permit_number: 'MP-2024-5678',
      permit_type: 'Monthly',
      enforcement_action: null,
      violation_id: null,
      discount_applied: 15.00,
      tax_amount: 10.80,
      total_amount: 145.80,
      status: 'Completed',
      processed_by: 'Admin User',
      notes: 'Monthly permit renewal with early bird discount',
      entry_time: null,
      exit_time: null,
      space_number: 'Reserved',
      zone: 'Monthly Zone',
      card_last_four: '8765',
      auth_code: 'AUTH123457',
      payment_gateway: 'Square',
      processor_fee: 4.37,
      created_at: '11/18/2024 10:30:15',
      updated_at: '11/18/2024 10:30:15',
      ip_address: '192.168.1.101',
      user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'
    },
    {
      id: 3,
      transaction_id: 'TXN-2024-001236',
      date: '11/18/2024',
      time: '11:45 AM',
      location: '54 Flagler',
      license_plate: 'DEF456',
      customer_name: null,
      transaction_type: 'Violation Payment',
      duration: null,
      pricing_mode: 'Fixed Fine',
      amount: 75.00,
      payment_method: 'Mobile Payment',
      payment_reference: 'REF-789014',
      permit_number: null,
      permit_type: null,
      enforcement_action: 'Ticket Issued',
      violation_id: 'VIO-2024-001234',
      discount_applied: null,
      tax_amount: 0.00,
      total_amount: 75.00,
      status: 'Completed',
      processed_by: 'Officer Martinez',
      notes: 'Expired meter violation payment',
      entry_time: null,
      exit_time: null,
      space_number: 'B-22',
      zone: 'Metered Zone',
      card_last_four: null,
      auth_code: 'MOBILE123458',
      payment_gateway: 'PayPal',
      processor_fee: 2.18,
      created_at: '11/18/2024 11:45:30',
      updated_at: '11/18/2024 11:45:30',
      ip_address: '192.168.1.102',
      user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15'
    },
    {
      id: 4,
      transaction_id: 'TXN-2024-001237',
      date: '11/18/2024',
      time: '12:00 PM',
      location: '18 Lincoln',
      license_plate: 'GHI789',
      customer_name: 'Michael Brown',
      transaction_type: 'Employee Permit',
      duration: null,
      pricing_mode: 'Employee Rate',
      amount: 50.00,
      payment_method: 'Bank Transfer',
      payment_reference: 'REF-789015',
      permit_number: 'EP-2024-9012',
      permit_type: 'Employee',
      enforcement_action: null,
      violation_id: null,
      discount_applied: null,
      tax_amount: 4.00,
      total_amount: 54.00,
      status: 'Pending',
      processed_by: 'HR Department',
      notes: 'New employee permit application',
      entry_time: null,
      exit_time: null,
      space_number: 'Employee Lot',
      zone: 'Employee Zone',
      card_last_four: null,
      auth_code: 'BANK123459',
      payment_gateway: 'ACH Direct',
      processor_fee: 1.00,
      created_at: '11/18/2024 12:00:00',
      updated_at: '11/18/2024 12:00:00',
      ip_address: '192.168.1.103',
      user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    },
    {
      id: 5,
      transaction_id: 'TXN-2024-001238',
      date: '11/18/2024',
      time: '01:15 PM',
      location: '72 Park',
      license_plate: 'JKL012',
      customer_name: 'Emily Davis',
      transaction_type: 'VIP Permit',
      duration: null,
      pricing_mode: 'VIP Rate',
      amount: 300.00,
      payment_method: 'Credit Card',
      payment_reference: 'REF-789016',
      permit_number: 'VIP-2024-3456',
      permit_type: 'VIP',
      enforcement_action: null,
      violation_id: null,
      discount_applied: null,
      tax_amount: 24.00,
      total_amount: 324.00,
      status: 'Completed',
      processed_by: 'VIP Services',
      notes: 'Premium VIP parking permit with concierge services',
      entry_time: null,
      exit_time: null,
      space_number: 'VIP-01',
      zone: 'VIP Zone',
      card_last_four: '1234',
      auth_code: 'AUTH123460',
      payment_gateway: 'Stripe',
      processor_fee: 9.42,
      created_at: '11/18/2024 13:15:45',
      updated_at: '11/18/2024 13:15:45',
      ip_address: '192.168.1.104',
      user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'
    },
    {
      id: 6,
      transaction_id: 'TXN-2024-001239',
      date: '11/18/2024',
      time: '02:30 PM',
      location: 'Pacs',
      license_plate: 'MNO345',
      customer_name: 'Robert Wilson',
      transaction_type: 'Event Parking',
      duration: 240,
      pricing_mode: 'Event Rate',
      amount: 25.00,
      payment_method: 'Cash',
      payment_reference: null,
      permit_number: null,
      permit_type: null,
      enforcement_action: null,
      violation_id: null,
      discount_applied: 5.00,
      tax_amount: 1.60,
      total_amount: 21.60,
      status: 'Completed',
      processed_by: 'Attendant Smith',
      notes: 'Special event parking with promotional discount',
      entry_time: '02:30 PM',
      exit_time: '06:30 PM',
      space_number: 'C-08',
      zone: 'Event Zone',
      card_last_four: null,
      auth_code: 'CASH123461',
      payment_gateway: 'Cash Register',
      processor_fee: 0.00,
      created_at: '11/18/2024 14:30:12',
      updated_at: '11/18/2024 18:30:25',
      ip_address: '192.168.1.105',
      user_agent: 'POS Terminal v2.1'
    },
    {
      id: 7,
      transaction_id: 'TXN-2024-001240',
      date: '11/18/2024',
      time: '03:45 PM',
      location: '11 ST',
      license_plate: 'PQR678',
      customer_name: 'Lisa Anderson',
      transaction_type: 'Hourly Parking',
      duration: 90,
      pricing_mode: 'Progressive Price',
      amount: 12.50,
      payment_method: 'Credit Card',
      payment_reference: 'REF-789017',
      permit_number: null,
      permit_type: null,
      enforcement_action: null,
      violation_id: null,
      discount_applied: null,
      tax_amount: 1.00,
      total_amount: 13.50,
      status: 'Failed',
      processed_by: 'System Auto',
      notes: 'Payment declined - insufficient funds',
      entry_time: '03:45 PM',
      exit_time: '05:15 PM',
      space_number: 'D-12',
      zone: 'Zone D',
      card_last_four: '9876',
      auth_code: 'DECLINED',
      payment_gateway: 'Stripe',
      processor_fee: 0.00,
      created_at: '11/18/2024 15:45:18',
      updated_at: '11/18/2024 17:15:22',
      ip_address: '192.168.1.106',
      user_agent: 'Mozilla/5.0 (Android 13; Mobile; rv:109.0) Gecko/111.0 Firefox/111.0'
    },
    {
      id: 8,
      transaction_id: 'TXN-2024-001241',
      date: '11/18/2024',
      time: '04:00 PM',
      location: '54 Flagler',
      license_plate: 'STU901',
      customer_name: 'David Martinez',
      transaction_type: 'Hourly Parking',
      duration: 180,
      pricing_mode: 'Time Window',
      amount: 20.00,
      payment_method: 'Debit Card',
      payment_reference: 'REF-789018',
      permit_number: null,
      permit_type: null,
      enforcement_action: null,
      violation_id: null,
      discount_applied: null,
      tax_amount: 1.60,
      total_amount: 21.60,
      status: 'Refunded',
      processed_by: 'Customer Service',
      notes: 'Refunded due to equipment malfunction',
      entry_time: '04:00 PM',
      exit_time: '07:00 PM',
      space_number: 'E-05',
      zone: 'Zone E',
      card_last_four: '5432',
      auth_code: 'AUTH123462',
      payment_gateway: 'Square',
      processor_fee: 0.63,
      created_at: '11/18/2024 16:00:30',
      updated_at: '11/18/2024 19:00:45',
      ip_address: '192.168.1.107',
      user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    },
    {
      id: 9,
      transaction_id: 'TXN-2024-001242',
      date: '11/18/2024',
      time: '05:30 PM',
      location: '18 Lincoln',
      license_plate: 'VWX234',
      customer_name: 'Jennifer Taylor',
      transaction_type: 'Hourly Parking',
      duration: 60,
      pricing_mode: 'Fixed Hourly',
      amount: 8.00,
      payment_method: 'Mobile Payment',
      payment_reference: 'REF-789019',
      permit_number: null,
      permit_type: null,
      enforcement_action: null,
      violation_id: null,
      discount_applied: null,
      tax_amount: 0.64,
      total_amount: 8.64,
      status: 'Disputed',
      processed_by: 'Dispute Team',
      notes: 'Customer disputes parking duration calculation',
      entry_time: '05:30 PM',
      exit_time: '06:30 PM',
      space_number: 'F-18',
      zone: 'Zone F',
      card_last_four: null,
      auth_code: 'MOBILE123463',
      payment_gateway: 'Apple Pay',
      processor_fee: 0.25,
      created_at: '11/18/2024 17:30:15',
      updated_at: '11/18/2024 18:30:20',
      ip_address: '192.168.1.108',
      user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15'
    },
    {
      id: 10,
      transaction_id: 'TXN-2024-001243',
      date: '11/18/2024',
      time: '06:15 PM',
      location: '72 Park',
      license_plate: 'YZA567',
      customer_name: 'Christopher Lee',
      transaction_type: 'Hourly Parking',
      duration: 150,
      pricing_mode: 'Progressive Price',
      amount: 18.75,
      payment_method: 'Credit Card',
      payment_reference: 'REF-789020',
      permit_number: null,
      permit_type: null,
      enforcement_action: null,
      violation_id: null,
      discount_applied: null,
      tax_amount: 1.50,
      total_amount: 20.25,
      status: 'Completed',
      processed_by: 'System Auto',
      notes: 'Evening parking with progressive pricing',
      entry_time: '06:15 PM',
      exit_time: '08:45 PM',
      space_number: 'G-25',
      zone: 'Zone G',
      card_last_four: '2468',
      auth_code: 'AUTH123464',
      payment_gateway: 'Stripe',
      processor_fee: 0.59,
      created_at: '11/18/2024 18:15:40',
      updated_at: '11/18/2024 20:45:55',
      ip_address: '192.168.1.109',
      user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'
    }
  ];

  const initialData = {
    transactions: mockTransactions
  };

  return <TransactionReportsInteractive initialData={initialData} />;
}